### ISSUE TITLE
Erro no Build do Backend

### ISSUE THREAD

**Issue by marksamp** [cleitonme/izing.open.io#3]
Estou tendo o seguinte problema no momento do build do backend, usando o comando npm build --force

`npm ERR! code 1
npm ERR! path /www/wwwroot/plataforma/backend/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! /www/wwwroot/plataforma/backend/node_modules/sharp/node_modules/tar-fs/index.js:6
npm ERR! const win32 = (global.Bare?.platform || process.platform) === 'win32'
npm ERR!                            ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token '.'
npm ERR!     at wrapSafe (internal/modules/cjs/loader.js:915:16)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:963:27)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:85:18)
npm ERR!     at Object.<anonymous> (/www/wwwroot/plataforma/backend/node_modules/sharp/install/libvips.js:18:15)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marcio/.npm/_logs/2024-11-09T06_36_50_271Z-debug-0.log`

**Comment by cleitonme** [comment]
https://github.com/cleitonme/izing.open.io/blob/master/docs/INSTALL_VPS_UBUNTU_20_22.md
